apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: database-claim1
    file:
      - init-db.d

resources:
  #MongoDB
  - database-claim0-persistentvolumeclaim.yaml
  - database-claim1-persistentvolumeclaim.yaml
  - database-claim2-persistentvolumeclaim.yaml
  - database-deployment.yaml
  - database-service.yaml
  ##Express
  - express-deployment.yaml
  - express-service.yaml
    #Nginx
  - nginx-deployment.yaml
  - nginx-service.yaml
  #Angular
  - angular-deployment.yaml
  - angular-service.yaml
